[2024-03-10T13:17:21.096+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: netflix_etl_dag.is_api_available manual__2024-03-10T13:17:18.171216+00:00 [queued]>
[2024-03-10T13:17:21.115+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: netflix_etl_dag.is_api_available manual__2024-03-10T13:17:18.171216+00:00 [queued]>
[2024-03-10T13:17:21.116+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 3
[2024-03-10T13:17:21.155+0000] {taskinstance.py:2214} INFO - Executing <Task(HttpSensor): is_api_available> on 2024-03-10 13:17:18.171216+00:00
[2024-03-10T13:17:21.161+0000] {standard_task_runner.py:60} INFO - Started process 610 to run task
[2024-03-10T13:17:21.167+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'netflix_etl_dag', 'is_api_available', 'manual__2024-03-10T13:17:18.171216+00:00', '--job-id', '27', '--raw', '--subdir', 'DAGS_FOLDER/netflix_dag.py', '--cfg-path', '/tmp/tmp99pzh_h7']
[2024-03-10T13:17:21.171+0000] {standard_task_runner.py:88} INFO - Job 27: Subtask is_api_available
[2024-03-10T13:17:21.292+0000] {task_command.py:423} INFO - Running <TaskInstance: netflix_etl_dag.is_api_available manual__2024-03-10T13:17:18.171216+00:00 [running]> on host aaa4b1109113
[2024-03-10T13:17:21.411+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='anamsken60@gmail.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='netflix_etl_dag' AIRFLOW_CTX_TASK_ID='is_api_available' AIRFLOW_CTX_EXECUTION_DATE='2024-03-10T13:17:18.171216+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-03-10T13:17:18.171216+00:00'
[2024-03-10T13:17:21.412+0000] {http.py:137} INFO - Poking: unogs/
[2024-03-10T13:17:21.423+0000] {base.py:83} INFO - Using connection ID 'netflix_api' for task execution.
[2024-03-10T13:17:22.054+0000] {http.py:192} ERROR - HTTP error: Not Found
[2024-03-10T13:17:22.056+0000] {http.py:193} ERROR - {"message":"no Route matched with those values"}
[2024-03-10T13:18:22.115+0000] {http.py:137} INFO - Poking: unogs/
[2024-03-10T13:18:22.126+0000] {base.py:83} INFO - Using connection ID 'netflix_api' for task execution.
[2024-03-10T13:18:38.653+0000] {http.py:192} ERROR - HTTP error: Not Found
[2024-03-10T13:18:38.654+0000] {http.py:193} ERROR - {"message":"no Route matched with those values"}
[2024-03-10T13:19:38.719+0000] {http.py:137} INFO - Poking: unogs/
[2024-03-10T13:19:38.822+0000] {base.py:83} INFO - Using connection ID 'netflix_api' for task execution.
[2024-03-10T13:19:39.364+0000] {http.py:192} ERROR - HTTP error: Not Found
[2024-03-10T13:19:39.365+0000] {http.py:193} ERROR - {"message":"no Route matched with those values"}
[2024-03-10T13:20:39.366+0000] {http.py:137} INFO - Poking: unogs/
[2024-03-10T13:20:39.378+0000] {base.py:83} INFO - Using connection ID 'netflix_api' for task execution.
[2024-03-10T13:20:52.591+0000] {http.py:192} ERROR - HTTP error: Not Found
[2024-03-10T13:20:52.593+0000] {http.py:193} ERROR - {"message":"no Route matched with those values"}
[2024-03-10T13:21:52.641+0000] {http.py:137} INFO - Poking: unogs/
[2024-03-10T13:21:52.652+0000] {base.py:83} INFO - Using connection ID 'netflix_api' for task execution.
[2024-03-10T13:21:53.352+0000] {http.py:192} ERROR - HTTP error: Not Found
[2024-03-10T13:21:53.354+0000] {http.py:193} ERROR - {"message":"no Route matched with those values"}
[2024-03-10T13:22:53.411+0000] {http.py:137} INFO - Poking: unogs/
[2024-03-10T13:22:53.441+0000] {base.py:83} INFO - Using connection ID 'netflix_api' for task execution.
[2024-03-10T13:22:55.273+0000] {http.py:192} ERROR - HTTP error: Not Found
[2024-03-10T13:22:55.274+0000] {http.py:193} ERROR - {"message":"no Route matched with those values"}
[2024-03-10T13:23:55.319+0000] {http.py:137} INFO - Poking: unogs/
[2024-03-10T13:23:55.349+0000] {base.py:83} INFO - Using connection ID 'netflix_api' for task execution.
[2024-03-10T13:23:55.931+0000] {http.py:192} ERROR - HTTP error: Not Found
[2024-03-10T13:23:55.932+0000] {http.py:193} ERROR - {"message":"no Route matched with those values"}
[2024-03-10T13:24:55.965+0000] {http.py:137} INFO - Poking: unogs/
[2024-03-10T13:24:55.979+0000] {base.py:83} INFO - Using connection ID 'netflix_api' for task execution.
[2024-03-10T13:24:56.502+0000] {http.py:192} ERROR - HTTP error: Not Found
[2024-03-10T13:24:56.503+0000] {http.py:193} ERROR - {"message":"no Route matched with those values"}
[2024-03-10T13:25:56.528+0000] {http.py:137} INFO - Poking: unogs/
[2024-03-10T13:25:56.538+0000] {base.py:83} INFO - Using connection ID 'netflix_api' for task execution.
[2024-03-10T13:25:57.078+0000] {http.py:192} ERROR - HTTP error: Not Found
[2024-03-10T13:25:57.079+0000] {http.py:193} ERROR - {"message":"no Route matched with those values"}
[2024-03-10T13:26:57.137+0000] {http.py:137} INFO - Poking: unogs/
[2024-03-10T13:26:57.145+0000] {base.py:83} INFO - Using connection ID 'netflix_api' for task execution.
[2024-03-10T13:26:57.848+0000] {http.py:192} ERROR - HTTP error: Not Found
[2024-03-10T13:26:57.849+0000] {http.py:193} ERROR - {"message":"no Route matched with those values"}
[2024-03-10T13:27:57.799+0000] {http.py:137} INFO - Poking: unogs/
[2024-03-10T13:27:57.814+0000] {base.py:83} INFO - Using connection ID 'netflix_api' for task execution.
[2024-03-10T13:27:58.474+0000] {http.py:192} ERROR - HTTP error: Not Found
[2024-03-10T13:27:58.475+0000] {http.py:193} ERROR - {"message":"no Route matched with those values"}
[2024-03-10T13:28:58.530+0000] {http.py:137} INFO - Poking: unogs/
[2024-03-10T13:28:58.542+0000] {base.py:83} INFO - Using connection ID 'netflix_api' for task execution.
[2024-03-10T13:28:59.209+0000] {http.py:192} ERROR - HTTP error: Not Found
[2024-03-10T13:28:59.213+0000] {http.py:193} ERROR - {"message":"no Route matched with those values"}
[2024-03-10T13:29:59.275+0000] {http.py:137} INFO - Poking: unogs/
[2024-03-10T13:29:59.291+0000] {base.py:83} INFO - Using connection ID 'netflix_api' for task execution.
[2024-03-10T13:29:59.876+0000] {http.py:192} ERROR - HTTP error: Not Found
[2024-03-10T13:29:59.883+0000] {http.py:193} ERROR - {"message":"no Route matched with those values"}
